# NOTE: this will change, depending on the configurables based on the funnel optimization analyst
SIM_CONFIG = {
    "random_seed": 42,
    "as_of_date": "2024-12-31",
    "target_users": 1000000,
    "n_workers": 8,
    "channels": ["organic", "meta", "tiktok", "direct"],
    "utm_maps": {
        "organic": {
            "source": ["google", "bing", "yahoo", "duckduckgo"],
            "source_weights": [0.95, 0.03, 0.01, 0.01],
            "medium": ["organic"],
            "medium_weights": [1.0],
            "campaign": ["(not_set)"],
            "campaign_weights": [1.0],
        },
        "meta": {
            "source": ["facebook", "ig", "messenger"],
            "source_weights": [0.75, 0.15, 0.10],
            "medium": ["social", "cpc"],
            "medium_weights": [0.30, 0.70],
            "campaign": [
                "spring_sale",
                "retargeting",
                "brand_awareness",
                "influencer_collab",
            ],
            "campaign_weights": [0.40, 0.30, 0.20, 0.10],
        },
        "tiktok": {
            "source": ["tiktok"],
            "source_weights": [1.0],
            "medium": ["affiliate", "live", "cpc"],
            "medium_weights": [0.50, 0.30, 0.20],
            "campaign": [
                "summer_vibes",
                "creator_fund",
                "flash_sale",
                "viral_challenge",
            ],
            "campaign_weights": [0.30, 0.20, 0.30, 0.20],
        },
        "direct": {
            "source": ["(direct)"],
            "source_weights": [1.0],
            "medium": ["(none)"],
            "medium_weights": [1.0],
            "campaign": ["(not_set)"],
            "campaign_weights": [1.0],
        },
    },
    "base_session_interval_days": 45.0,
    "burst_session_weights": [0.70, 0.30],
    "literacy_max_score": 10.0,
    "literacy_session_boost_weight": 2.0,
    "shift_probability": 0.12,
    "average_dropoff": 5,
    "diurnal_behavior_types": ["baseline", "lunch_rush", "evening_rush"],
    "diurnal_behavior_weights": [0.25, 0.25, 0.50],
    "session_base_max_seconds": 300,
    "session_base_min_seconds": 10,
    "os_types": ["android", "ios", "windows", "macos"],
    "os_weights_by_income": {
        "low": [0.36, 0.26, 0.22, 0.16],
        "mid": [0.32, 0.22, 0.26, 0.20],
        "high": [0.25, 0.30, 0.25, 0.20],
    },
    "income_os_thresholds": [0.65, 1.4],
    "android_software_version": [14, 13, 12, 11],
    "android_software_version_weights": [0.5, 0.3, 0.15, 0.05],
    "ios_software_version": ["17.3", "16.5", "15.2"],
    "ios_software_version_weights": [0.6, 0.3, 0.1],
    "windows_software_version": ["11", "10"],
    "windows_software_version_weights": [0.7, 0.3],
    "macos_software_version": ["sonoma", "ventura", "monterey"],
    "macos_software_version_weights": [0.3, 0.4, 0.3],
    "digital_literacy_reduction": 150,
    "android_error_rate": 0.05,
    "android_error_string": "ERR_VERSION_NOT_FOUND",
    "average_wait": 30,
    "base_transactions": {
        # top of funnel
        "search": {"view_item_list": 0.70, "drop_off": 0.30},
        "view_item_list": {"select_item": 0.60, "search": 0.20, "drop_off": 0.20},
        "select_item": {"view_item": 0.80, "view_item_list": 0.10, "drop_off": 0.10},
        # mid funnel
        "view_item": {
            "add_to_cart": 0.30,
            "add_to_wishlist": 0.10,
            "share": 0.05,
            "view_item_list": 0.25,
            "drop_off": 0.30,
        },
        "add_to_wishlist": {"view_item": 0.60, "drop_off": 0.40},
        "share": {"view_item": 0.50, "drop_off": 0.50},
        # cart management
        "add_to_cart": {
            "view_cart": 0.50,
            "view_item": 0.30,
            "remove_from_cart": 0.05,
            "drop_off": 0.15,
        },
        "remove_from_cart": {"view_cart": 0.40, "view_item": 0.30, "drop_off": 0.30},
        "view_cart": {"begin_checkout": 0.50, "view_item": 0.20, "drop_off": 0.30},
        "begin_checkout": {
            # checkout flow
            "add_shipping_info": 0.70,
            "view_cart": 0.10,
            "drop_off": 0.20,
        },
        "add_shipping_info": {
            "add_payment_info": 0.80,
            "view_cart": 0.05,
            "drop_off": 0.15,
        },
        "add_payment_info": {"purchase": 0.85, "view_cart": 0.05, "drop_off": 0.10},
        # post-purchase
        "purchase": {"generate_lead": 0.20, "refund": 0.01, "drop_off": 0.79},
        "generate_lead": {"drop_off": 1.0},
        "refund": {"drop_off": 1.0},
        "drop_off": {"drop_off": 1.0},
    },
    "items_per_order_counts": [1, 2, 3, 4, 5],
    "items_per_order_weights": [0.50, 0.30, 0.10, 0.05, 0.05],
    "item_quantity_counts": [1, 2, 3, 5],
    "item_quantity_weights": [0.85, 0.10, 0.04, 0.01],
    "item_categories": [
        "beauty_and_personal_care",
        "fashion_and_apparel",
        "food_and_beverage",
        "baby_and_kids",
        "lifestyle_and_fitness",
        "furniture_and_home_appliances",
        "consumer_electronics",
    ],
    "item_category_weights": [0.263, 0.192, 0.137, 0.137, 0.099, 0.095, 0.077],
    "category_base_prices": {
        "beauty_and_personal_care": 250.00,
        "fashion_and_apparel": 350.00,
        "food_and_beverage": 150.00,
        "baby_and_kids": 400.00,
        "lifestyle_and_fitness": 500.00,
        "furniture_and_home_appliances": 3000.00,
        "consumer_electronics": 4000.00,
    },
    "promo_code_probability": 0.25,
    "promo_discount_tiers": [0.10, 0.15, 0.20, 0.50],
    "promo_discount_weights": [0.50, 0.30, 0.15, 0.05],
    "promo_discount_caps": [50.0, 100.0, 150.0, 250.0],
    "payment_type": [
        "digital_wallet",
        "credit_card",
        "bank_transfer",
        "cod",
        "debit_card",
        "cash_payments",
        "buy_now_pay_later",
    ],
    "payment_type_weights": [0.35, 0.21, 0.16, 0.13, 0.11, 0.03, 0.01],
    "income_payment_thresholds": [0.5, 1.5],
    "payment_weights_by_income": {
        "low": [0.45, 0.00, 0.00, 0.40, 0.00, 0.10, 0.05],
        "mid": [0.35, 0.10, 0.05, 0.25, 0.05, 0.05, 0.15],
        "high": [0.20, 0.45, 0.20, 0.05, 0.05, 0.00, 0.05],
    },
    "dup_rate_events": 0.005,
    "outlier_rate_session_duration": 0.01,
    "outlier_duration_multiplier": 10,
    "outlier_rate_item_price": 0.005,
    "outlier_price_multiplier": 100,
    "channel_weights_by_literacy": {
        "low": [0.50, 0.20, 0.25, 0.05],
        "mid": [0.38, 0.32, 0.18, 0.12],
        "high": [0.25, 0.35, 0.10, 0.30],
    },
    "literacy_thresholds": [0.33, 0.67],
    "payday_dates": [15, 30],
    "payday_boost": 1.3,
    "funnel_view_item_literacy_effect": 0.08,
    "funnel_view_item_mobile_penalty": 0.05,
    "funnel_checkout_trust_effect": 0.15,
    "funnel_checkout_trust_mean": 0.286,
    "regions": {
        "ncr": {
            "weight": 0.13,
            "cities": [
                "caloocan",
                "las_piñas",
                "makati",
                "malabon",
                "mandaluyong",
                "manila",
                "marikina",
                "muntinlupa",
                "navotas",
                "parañaque",
                "pasay",
                "pasig",
                "pateros",
                "quezon_city",
                "san_juan",
                "taguig",
                "valenzuela",
            ],
            "city_weights": [
                0.10,
                0.04,
                0.08,
                0.02,
                0.03,
                0.15,
                0.04,
                0.03,
                0.02,
                0.04,
                0.03,
                0.08,
                0.01,
                0.20,
                0.01,
                0.07,
                0.05,
            ],
        },
        "car": {
            "weight": 0.02,
            "cities": [
                "abra",
                "apayao",
                "baguio",
                "benguet",
                "ifugao",
                "kalinga",
                "mountain_province",
            ],
            "city_weights": [0.10, 0.10, 0.30, 0.20, 0.10, 0.10, 0.10],
        },
        "region_i": {
            "weight": 0.05,
            "cities": ["ilocos_norte", "ilocos_sur", "la_union", "pangasinan"],
            "city_weights": [0.15, 0.15, 0.15, 0.55],
        },
        "region_ii": {
            "weight": 0.03,
            "cities": ["batanes", "cagayan", "isabela", "nueva_vizcaya", "quirino"],
            "city_weights": [0.02, 0.35, 0.45, 0.10, 0.08],
        },
        "region_iii": {
            "weight": 0.11,
            "cities": [
                "aurora",
                "bataan",
                "bulacan",
                "nueva_ecija",
                "pampanga",
                "tarlac",
                "zambales",
            ],
            "city_weights": [0.03, 0.07, 0.30, 0.20, 0.25, 0.10, 0.05],
        },
        "region_iv-a": {
            "weight": 0.15,
            "cities": ["batangas", "cavite", "laguna", "quezon", "rizal"],
            "city_weights": [0.18, 0.25, 0.25, 0.12, 0.20],
        },
        "region_iv-b": {
            "weight": 0.03,
            "cities": ["marinduque", "mindoro", "palawan", "romblon"],
            "city_weights": [0.10, 0.40, 0.40, 0.10],
        },
        "region_v": {
            "weight": 0.06,
            "cities": [
                "albay",
                "camarines_norte",
                "camarines_sur",
                "catanduanes",
                "masbate",
                "sorsogon",
            ],
            "city_weights": [0.25, 0.10, 0.35, 0.05, 0.10, 0.15],
        },
        "region_vi": {
            "weight": 0.07,
            "cities": ["aklan", "antique", "capiz", "guimaras", "iloilo"],
            "city_weights": [0.15, 0.10, 0.20, 0.05, 0.50],
        },
        "nir": {
            "weight": 0.04,
            "cities": ["negros_occidental", "negros_oriental", "siquijor"],
            "city_weights": [0.65, 0.30, 0.05],
        },
        "region_vii": {
            "weight": 0.07,
            "cities": ["bohol", "cebu"],
            "city_weights": [0.25, 0.75],
        },
        "region_viii": {
            "weight": 0.04,
            "cities": [
                "biliran",
                "eastern_samar",
                "leyte",
                "northern_samar",
                "samar",
                "southern_leyte",
            ],
            "city_weights": [0.03, 0.10, 0.45, 0.15, 0.20, 0.07],
        },
        "region_ix": {
            "weight": 0.03,
            "cities": [
                "sulu",
                "zamboanga_del_norte",
                "zamboanga_del_sur",
                "zamboanga_sibugay",
            ],
            "city_weights": [0.15, 0.30, 0.40, 0.15],
        },
        "region_x": {
            "weight": 0.05,
            "cities": [
                "bukidnon",
                "camiguin",
                "lanao_del_norte",
                "misamis_occidental",
                "misamis_oriental",
            ],
            "city_weights": [0.25, 0.03, 0.20, 0.12, 0.40],
        },
        "region_xi": {
            "weight": 0.05,
            "cities": [
                "davao_de_oro",
                "davao_del_norte",
                "davao_del_sur",
                "davao_occidental",
                "davao_oriental",
            ],
            "city_weights": [0.15, 0.20, 0.50, 0.05, 0.10],
        },
        "region_xii": {
            "weight": 0.04,
            "cities": ["sarangani", "south_cotabato", "sultan_kudarat"],
            "city_weights": [0.15, 0.60, 0.25],
        },
        "region_xiii": {
            "weight": 0.02,
            "cities": [
                "agusan_del_norte",
                "agusan_del_sur",
                "dinagat_islands",
                "surigao_del_norte",
                "surigao_del_sur",
            ],
            "city_weights": [0.30, 0.25, 0.05, 0.20, 0.20],
        },
        "barmm": {
            "weight": 0.01,
            "cities": [
                "basilan",
                "lanao_del_sur",
                "maguindanao_del_norte",
                "maguindanao_del_sur",
                "tawi-tawi",
            ],
            "city_weights": [0.10, 0.35, 0.25, 0.20, 0.10],
        },
    },
}
