# NOTE: this will change, depending on the configurables based on the funnel optimization analyst
SIM_CONFIG = {
    "random_seed": 42,
    "as_of_date": "2024-12-31",
    "target_users": 1000000,
    "n_workers": 1,
    "android_share": 0.65,
    "ios_share": 0.35,
    "channels": ["Organic", "Facebook", "TikTok", "Direct"],
    "channel_weights": [0.40, 0.30, 0.20, 0.10],
    "session_count": [1, 2, 3, 4, 5, 8, 15],
    "session_count_weights": [0.65, 0.15, 0.08, 0.05, 0.04, 0.02, 0.01],
    "burst_session_weights": [0.70, 0.30],
    "average_dropoff": 5,
    "peak_hours": [13, 21],
    "session_base_max_seconds": 300,
    "session_base_min_seconds": 10,
    "os_distribution": ["Android", "iOS", "Windows", "macOS"],
    "os_weights": [0.40, 0.25, 0.20, 0.15],
    "os_by_income": {
        "low": [0.36, 0.26, 0.22, 0.16],
        "mid": [0.32, 0.22, 0.26, 0.20],
        "high": [0.25, 0.30, 0.25, 0.20],
    },
    "income_os_thresholds": [0.65, 1.4],
    "android_software_version": [14, 13, 12, 11],
    "android_software_version_weights": [0.5, 0.3, 0.15, 0.05],
    "ios_software_version": ["17.3", "16.5", "15.2"],
    "ios_software_version_weights": [0.6, 0.3, 0.1],
    "windows_software_version": ["11", "10"],
    "windows_software_version_weights": [0.7, 0.3],
    "macos_software_version": ["Sonoma", "Ventura", "Monterey"],
    "digital_literacy_reduction": 150,
    "android_error_rate": 0.05,
    "android_error_string": "ERR_VERSION_NOT_FOUND",
    # events config
    "event_spacing_scale_seconds": 30,
    "base_transactions": {
        # Top of Funnel
        "search": {"view_item_list": 0.70, "drop_off": 0.30},
        "view_item_list": {"select_item": 0.60, "search": 0.20, "drop_off": 0.20},
        "select_item": {"view_item": 0.80, "view_item_list": 0.10, "drop_off": 0.10},
        # Mid Funnel
        "view_item": {
            "add_to_cart": 0.30,
            "add_to_wishlist": 0.10,
            "share": 0.05,
            "view_item_list": 0.25,
            "drop_off": 0.30,
        },
        "add_to_wishlist": {"view_item": 0.60, "drop_off": 0.40},
        "share": {"view_item": 0.50, "drop_off": 0.50},
        # Cart Management
        "add_to_cart": {
            "view_cart": 0.50,
            "view_item": 0.30,
            "remove_from_cart": 0.05,
            "drop_off": 0.15,
        },
        "remove_from_cart": {"view_cart": 0.40, "view_item": 0.30, "drop_off": 0.30},
        "view_cart": {"begin_checkout": 0.50, "view_item": 0.20, "drop_off": 0.30},
        # Checkout Flow
        "begin_checkout": {
            "add_shipping_info": 0.70,
            "view_cart": 0.10,
            "drop_off": 0.20,
        },
        "add_shipping_info": {
            "add_payment_info": 0.80,
            "view_cart": 0.05,
            "drop_off": 0.15,
        },
        "add_payment_info": {"purchase": 0.85, "view_cart": 0.05, "drop_off": 0.10},
        # Post-Purchase
        "purchase": {"generate_lead": 0.20, "refund": 0.01, "drop_off": 0.79},
        "generate_lead": {"drop_off": 1.0},
        "refund": {"drop_off": 1.0},
        "drop_off": {"drop_off": 1.0},
    },
    "items_per_order_counts": [1, 2, 3, 4, 5],
    "items_per_order_weights": [0.50, 0.30, 0.10, 0.05, 0.05],
    "item_quantity_counts": [1, 2, 3, 5],
    "item_quantity_weights": [0.85, 0.10, 0.04, 0.01],
    "product_categories": [
        "Fashion and apparel",
        "Beauty and personal care",
        "Food and beverage",
        "Consumer electronics",
        "Furniture and home appliances",
        "Lifestyle and fitness",
        "Baby and Kids",
    ],
    "product_category_weights": [0.20, 0.20, 0.15, 0.15, 0.10, 0.10, 0.10],
    "category_base_prices": {
        "Fashion and apparel": 35.00,
        "Beauty and personal care": 250.00,
        "Food and beverage": 85.00,
        "Consumer electronics": 15.00,
        "Furniture and home appliances": 26.00,
        "Lifestyle and fitness": 50.00,
        "Baby and Kids": 100.00,
    },
    "promo_code_probability": 0.25,
    "promo_discount_tiers": [0.10, 0.15, 0.20, 0.50],
    "promo_discount_weights": [0.50, 0.30, 0.15, 0.05],
    "payment_methods": [
        "Digital Wallet",
        "Credit Card",
        "Bank Transfer",
        "COD",
        "Debit Card",
        "Cash Payments",
        "Buy Now Pay Later",
    ],
    "payment_method_weights": [0.10, 0.10, 0.10, 0.15, 0.10, 0.25, 0.20],
    "dup_rate_events": 0.005,
    "outlier_rate_session_duration": 0.01,
    "outlier_duration_multiplier": 10,
    "outlier_rate_item_price": 0.005,
    "outlier_price_multiplier": 100,
    "channel_weights_by_literacy": {
        "low": [0.50, 0.20, 0.25, 0.05],
        "mid": [0.38, 0.32, 0.18, 0.12],
        "high": [0.25, 0.35, 0.10, 0.30],
    },
    "literacy_thresholds": [0.33, 0.67],
    "payday_dates": [15, 30],
    "payday_boost": 1.3,
    "funnel_view_item_literacy_effect": 0.08,
    "funnel_view_item_mobile_penalty": 0.05,
    "funnel_checkout_trust_effect": 0.15,
    "funnel_checkout_trust_mean": 0.286,
    "regions": {
        "NCR": {
            "weight": 0.13,
            "cities": [
                "Caloocan",
                "Las Piñas",
                "Makati",
                "Malabon",
                "Mandaluyong",
                "Manila",
                "Marikina",
                "Muntinlupa",
                "Navotas",
                "Parañaque",
                "Pasay",
                "Pasig",
                "Pateros",
                "Quezon City",
                "San Juan",
                "Taguig",
                "Valenzuela",
            ],
            "city_weights": [
                0.10,
                0.04,
                0.08,
                0.02,
                0.03,
                0.15,
                0.04,
                0.03,
                0.02,
                0.04,
                0.03,
                0.08,
                0.01,
                0.20,
                0.01,
                0.07,
                0.05,
            ],
        },
        "CAR": {
            "weight": 0.02,
            "cities": [
                "Abra",
                "Apayao",
                "Baguio",
                "Benguet",
                "Ifugao",
                "Kalinga",
                "Mountain Province",
            ],
            "city_weights": [0.10, 0.10, 0.30, 0.20, 0.10, 0.10, 0.10],
        },
        "Region I": {
            "weight": 0.05,
            "cities": ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
            "city_weights": [0.15, 0.15, 0.15, 0.55],
        },
        "Region II": {
            "weight": 0.03,
            "cities": ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
            "city_weights": [0.02, 0.35, 0.45, 0.10, 0.08],
        },
        "Region III": {
            "weight": 0.11,
            "cities": [
                "Aurora",
                "Bataan",
                "Bulacan",
                "Nueva Ecija",
                "Pampanga",
                "Tarlac",
                "Zambales",
            ],
            "city_weights": [0.03, 0.07, 0.30, 0.20, 0.25, 0.10, 0.05],
        },
        "Region IV-A": {
            "weight": 0.15,
            "cities": ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
            "city_weights": [0.18, 0.25, 0.25, 0.12, 0.20],
        },
        "Region IV-B": {
            "weight": 0.03,
            "cities": ["Marinduque", "Mindoro", "Palawan", "Romblon"],
            "city_weights": [0.10, 0.40, 0.40, 0.10],
        },
        "Region V": {
            "weight": 0.06,
            "cities": [
                "Albay",
                "Camarines Norte",
                "Camarines Sur",
                "Catanduanes",
                "Masbate",
                "Sorsogon",
            ],
            "city_weights": [0.25, 0.10, 0.35, 0.05, 0.10, 0.15],
        },
        "Region VI": {
            "weight": 0.07,
            "cities": ["Aklan", "Antique", "Capiz", "Guimaras", "Iloilo"],
            "city_weights": [0.15, 0.10, 0.20, 0.05, 0.50],
        },
        "NIR": {
            "weight": 0.04,
            "cities": ["Negros Occidental", "Negros Oriental", "Siquijor"],
            "city_weights": [0.65, 0.30, 0.05],
        },
        "Region VII": {
            "weight": 0.07,
            "cities": ["Bohol", "Cebu"],
            "city_weights": [0.25, 0.75],
        },
        "Region VIII": {
            "weight": 0.04,
            "cities": [
                "Biliran",
                "Eastern Samar",
                "Leyte",
                "Northern Samar",
                "Samar",
                "Southern Leyte",
            ],
            "city_weights": [0.03, 0.10, 0.45, 0.15, 0.20, 0.07],
        },
        "Region IX": {
            "weight": 0.03,
            "cities": [
                "Sulu",
                "Zamboanga del Norte",
                "Zamboanga del Sur",
                "Zamboanga Sibugay",
            ],
            "city_weights": [0.15, 0.30, 0.40, 0.15],
        },
        "Region X": {
            "weight": 0.05,
            "cities": [
                "Bukidnon",
                "Camiguin",
                "Lanao del Norte",
                "Misamis Occidental",
                "Misamis Oriental",
            ],
            "city_weights": [0.25, 0.03, 0.20, 0.12, 0.40],
        },
        "Region XI": {
            "weight": 0.05,
            "cities": [
                "Davao de Oro",
                "Davao del Norte",
                "Davao del Sur",
                "Davao Occidental",
                "Davao Oriental",
            ],
            "city_weights": [0.15, 0.20, 0.50, 0.05, 0.10],
        },
        "Region XII": {
            "weight": 0.04,
            "cities": ["Sarangani", "South Cotabato", "Sultan Kudarat"],
            "city_weights": [0.15, 0.60, 0.25],
        },
        "Region XIII": {
            "weight": 0.02,
            "cities": [
                "Agusan del Norte",
                "Agusan del Sur",
                "Dinagat Islands",
                "Surigao del Norte",
                "Surigao del Sur",
            ],
            "city_weights": [0.30, 0.25, 0.05, 0.20, 0.20],
        },
        "BARMM": {
            "weight": 0.01,
            "cities": [
                "Basilan",
                "Lanao del Sur",
                "Maguindanao del Norte",
                "Maguindanao del Sur",
                "Tawi-Tawi",
            ],
            "city_weights": [0.10, 0.35, 0.25, 0.20, 0.10],
        },
    },
}
